add stat service
Ilia28593/java-explore-with-me pull request #15
Opened 2023-11-07 19:22 UTC by Ilia28593

2023-11-09 06:39 UTC, krylov-sergey-sergeevich requested changes
Привет, в целом все неплохо, но давай мелочи обсудим.

2023-11-09 06:39 UTC, krylov-sergey-sergeevich commented on ewm-service/pom.xml
> +        <version>0.0.1-SNAPSHOT</version>
Почему так сделано?

2023-11-09 06:39 UTC, krylov-sergey-sergeevich commented on ewm-service/pom.xml
> +            <version>4.11</version>
Почему 4?

2023-11-09 06:39 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/java/ru/practicum/main/category/service/CategoryServiceImpl.java
> +            throw new DuplicateNameException("Duplicate category name");
в ошибке не указано какое имя дублируется - это не даст нам понимания при чтение логов

2023-11-09 06:39 UTC, krylov-sergey-sergeevich commented on stats/stats-server/src/main/java/ru/practicum/constant/Constants.java
> +    public static final String DATE_FORMAT = "yyyy-MM-dd HH:mm:ss";
Не дублируется разве?

2023-11-09 06:39 UTC, krylov-sergey-sergeevich commented on stats/stats-dto/pom.xml
> +            <version>4.11</version>
Опять 4 версия

2023-11-09 06:39 UTC, krylov-sergey-sergeevich commented on stats/stats-server/src/main/java/ru/practicum/exception/ErrorHandler.java
> +                .timestamp((LocalDateTime.now()).format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")))
DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss") - можно 1 раз создать и больше не будет дублей

2023-11-09 06:39 UTC, krylov-sergey-sergeevich commented on stats/stats-server/src/main/java/ru/practicum/exception/ErrorHandler.java
> +    private String error(Exception e) throws IOException {
А для чего так усложнено? Что данный метод делает

2023-11-09 06:39 UTC, krylov-sergey-sergeevich commented on stats/stats-server/src/main/java/ru/practicum/service/StatsServiceImpl.java
> +    public StatsServiceImpl(StatsRepository statsRepository) {
Ломбок может помочь убрать конструктор

2023-11-09 06:39 UTC, krylov-sergey-sergeevich commented on stats/stats-server/src/main/java/ru/practicum/service/StatsServiceImpl.java
> +            throw new IllegalArgumentException("The time of the end cannot be earlier than the time of the beginning!");
Есть текст, а данных которые относятся к ошибке нет

2023-11-09 09:49 UTC, Ilia28593 commented on stats/stats-server/src/main/java/ru/practicum/constant/Constants.java
> +    public static final String DATE_FORMAT = "yyyy-MM-dd HH:mm:ss";
нет по одному для каждого сервиса

2023-11-10 11:52 UTC, krylov-sergey-sergeevich approved these changes
Все хорошо - зачет


p.s просто удалять версию junit не лучшая практика, но терпимо

2023-11-10 12:56 UTC, merged